### ISSUE TITLE
 error: unrecognized arguments of tsv file

### ISSUE THREAD

**Issue by steffie11** [genomewalker/derep-genomes#11]
Hi. I have downloaded two plant genomes: Silene uniflora (GCA_018983105.1) and Picea abies (GCA_900067695.1). And I prepared a tsv file describing the taxonomic information.
genome$ cat test.tsv 
GCA_018983105.1	d__Eukaryota;p__Streptophyta;c__Magnoliopsida;o__Caryophyllales;f__Caryophyllaceae;g__Silene;s__Silene uniflora
GCA_900067695.1	d__Eukaryota;p__Streptophyta;c__Pinopsida;o__Pinales;f__Pinaceae;g__Picea;s__Picea abies

The two genomes and the tsv are in "genome" folder.
genome$ ls
GCA_018983105.1_ASM1898310v1_genomic.fna  GCA_900067695.1_Pabies01_genomic.fna  test.tsv

Then I ran derep, met the following error.
derepG --data genome --taxa genome/test.tsv
usage: derepG [-h] --data FILE [--db DB] [--workers INT] [--threads INT] [--slurm-threads INT] [--prefix PREFIX]
              [--tmp DIR] [--threshold FLOAT] [--xash-threshold FLOAT] [--max-assemblies INT] [--slurm-config FILE]
              [--chunk-size INT] [--slurm-arr-size INT] [--selected-taxa FILE] [--copy] [--dashing] [--out-dir OUT_DIR]
              [--min-genome-size INT] [--ani-fraglen-fraction FLOAT] [--debug] [--version]
derepG: error: unrecognized arguments: --taxa genome/test.tsv

I was wondering derep supports only genomes from GTDB or supports also genomes from NCBI. If it supports de-replicate plant genomes, do I have to convert from fna to fasta? Or there is a mistake in my tsv file? Thanks a lot for your help.

Cheers,
Sichao Huang

**Comment by genomewalker** [comment]
Hi @steffie11
I just updated the README. It had some remnants of the previous version. The `--taxa` has been removed from the current version. dereG just takes a TSV file using `--data` that must have the following columns: `accession,taxonomy,file`

Let me know if you have any other question
Antonio

**Comment by steffie11** [comment]
Thanks for the quick reply.

I removed flag --data and now it complains --data is missming. 

module load bio/derep/1.0.3 
derepG --taxa genome/test.tsv
usage: derepG [-h] --data FILE [--db DB] [--workers INT] [--threads INT] [--slurm-threads INT] [--prefix PREFIX]
              [--tmp DIR] [--threshold FLOAT] [--xash-threshold FLOAT] [--max-assemblies INT] [--slurm-config FILE]
              [--chunk-size INT] [--slurm-arr-size INT] [--selected-taxa FILE] [--copy] [--dashing] [--out-dir OUT_DIR]
              [--min-genome-size INT] [--ani-fraglen-fraction FLOAT] [--debug] [--version]
derepG: error: the following arguments are required: --data

Cheers,
Huang

**Comment by genomewalker** [comment]
You need to remove the `--taxa` and keep the data `--data`

**Comment by steffie11** [comment]
Thanks. 

Here I met an error about fastANI

(base) derepG --data genome/test.tsv
ERROR ::: 2022-11-23 18:45:28 ::: fastANI not found in PATH

Is there a mistake in the tsv file?
GCA_018983105.1	d__Eukaryota;p__Streptophyta;c__Magnoliopsida;o__Caryophyllales;f__Caryophyllaceae;g__Silene;s__Silene uniflora	genome/GCA_018983105.1_ASM1898310v1_genomic.fna
GCA_900067695.1	d__Eukaryota;p__Streptophyta;c__Pinopsida;o__Pinales;f__Pinaceae;g__Picea;s__Picea abies	genome/GCA_900067695.1_Pabies01_genomic.fna

Cheers,
Sichao

**Comment by genomewalker** [comment]
You need to install the environment with the necessary programs: https://github.com/genomewalker/derep-genomes#using-pip

**Comment by steffie11** [comment]
> You need to install the environment with the necessary programs: https://github.com/genomewalker/derep-genomes#using-pip

Hi I followed the tutorial by creating the virtual envrionment.
`(base) wget https://raw.githubusercontent.com/genomewalker/derep-genomes/master/environment.yml
--2022-11-24 13:56:31--  https://raw.githubusercontent.com/genomewalker/derep-genomes/master/environment.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 149 [text/plain]
Saving to: ‘environment.yml.3’

environment.yml.3         100%[===================================>]     149  --.-KB/s    in 0s      

2022-11-24 13:56:31 (18.3 MB/s) - ‘environment.yml.3’ saved [149/149]

(base) conda env create -f environment.yml

CondaValueError: prefix already exists: /home/ollie/shuang/miniconda3/envs/derep-genomes

(base) pip install derep-genomes
Requirement already satisfied: derep-genomes in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (1.0.3)
Requirement already satisfied: tqdm>=4.62.2 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from derep-genomes) (4.64.1)
Requirement already satisfied: simple-slurm>=0.2.2 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from derep-genomes) (0.2.5)
Requirement already satisfied: leidenalg>=0.8.2 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from derep-genomes) (0.9.0)
Requirement already satisfied: scipy>=1.5.2 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from derep-genomes) (1.9.3)
Requirement already satisfied: pandas>=1.1.2 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from derep-genomes) (1.4.4)
Requirement already satisfied: networkx>=2.5 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from derep-genomes) (2.8.8)
Requirement already satisfied: python-igraph>=0.8.3 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from derep-genomes) (0.10.2)
Requirement already satisfied: PyYAML>=5.4 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from derep-genomes) (6.0)
Requirement already satisfied: biopython>=1.78 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from derep-genomes) (1.78)
Requirement already satisfied: numpy in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from biopython>=1.78->derep-genomes) (1.23.3)
Requirement already satisfied: igraph<0.11,>=0.10.0 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from leidenalg>=0.8.2->derep-genomes) (0.10.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from pandas>=1.1.2->derep-genomes) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from pandas>=1.1.2->derep-genomes) (2022.1)
Requirement already satisfied: texttable>=1.6.2 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from igraph<0.11,>=0.10.0->leidenalg>=0.8.2->derep-genomes) (1.6.7)
Requirement already satisfied: six>=1.5 in /home/ollie/shuang/miniconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas>=1.1.2->derep-genomes) (1.16.0)`

But I failed to install the development version.

`pip install git+ssh://git@github.com/genomewalker/derep-genomes.git
Collecting git+ssh://****@github.com/genomewalker/derep-genomes.git
  Cloning ssh://****@github.com/genomewalker/derep-genomes.git to /work/ollie/tmp/pip-req-build-pl0vmww4
  Running command git clone --quiet 'ssh://****@github.com/genomewalker/derep-genomes.git' /work/ollie/tmp/pip-req-build-pl0vmww4
  Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  error: subprocess-exited-with-error
  
  × git clone --quiet 'ssh://****@github.com/genomewalker/derep-genomes.git' /work/ollie/tmp/pip-req-build-pl0vmww4 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --quiet 'ssh://****@github.com/genomewalker/derep-genomes.git' /work/ollie/tmp/pip-req-build-pl0vmww4 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(base) 
`

Then the fastANI error appears again.
(base) derepG --data genome/test.tsv
ERROR ::: 2022-11-24 13:59:31 ::: fastANI not found in PATH

Thank you very very much for the help.

Cheers,
Sichao

**Comment by genomewalker** [comment]
Hi @steffie11 

you should do:

```
wget https://raw.githubusercontent.com/genomewalker/derep-genomes/master/environment.yml
conda env create -f environment.yml
conda activate derep-genomes
pip install derep-genomes
```

In any case, the set of genomes you selected will not be de-replicated because derepG does the replication at the lowest rank in the taxonomy you provide, usually, it is at species level

Antonio

**Comment by steffie11** [comment]
Thanks. The two genomes that I selected are at species level. I followed your pipeline and installed derep-genomes. There is a dashing error.

(derep-genomes) derepG --data genome/test.tsv
ERROR ::: 2022-11-24 14:12:28 ::: dashing not found in PATH

Cheers,
Sichao

**Comment by genomewalker** [comment]
Hi @steffie11  

do :
```
conda install "dashing>=0.4.0"
```
derepG will treat each assembly independently and return both genomes as they belong to different species:
```
d__Eukaryota;p__Streptophyta;c__Magnoliopsida;o__Caryophyllales;f__Caryophyllaceae;g__Silene;s__Silene uniflora
d__Eukaryota;p__Streptophyta;c__Pinopsida;o__Pinales;f__Pinaceae;g__Picea;s__Picea abies
```
The main objective of derepG is to dereplicate assemblies within species, or any lowest rank.
