### ISSUE TITLE
ValueError: All objects passed were None

### ISSUE THREAD

**Issue by ShangjinTan** [genomewalker/derep-genomes#5]
Hi,

I have an error with running derep-genomes. Hope you can provide some clues. Details are as follows.

Thank you!

derep-genomes version: 0.0.19+0.ge35e89c.dirty

# **command:**
derepG --in-dir /hwfssz1/jin/20_phyto/27_genomes/01_test --taxa /hwfssz1/jin/20_phyto/27_genomes/02_file/tax.tsv --threads 10 --tmp /hwfssz1/jin/20_phyto/27_genomes/02t_file --copy --out-dir /hwfssz1/jin/20_phyto/27_genomes/03_derep

# **Log:**
INFO ::: 2022-03-03 15:14:13,485 ::: Found DB in derep-genomes.db
INFO ::: 2022-03-03 15:14:13,582 ::: Checking correct tables exist
INFO ::: 2022-03-03 15:14:13,585 ::: DB tables seem to be OK
INFO ::: 2022-03-03 15:14:13,585 ::: Finding assemblies in /hwfssz1/jin/20_phyto/27_genomes/01_test
INFO ::: 2022-03-03 15:14:13,586 ::: Found 4 files in /hwfssz1/jin/20_phyto/27_genomes/01_test
INFO ::: 2022-03-03 15:14:13,586 ::: Filtering taxa with assemblies
INFO ::: 2022-03-03 15:14:13,588 ::: Found 3 assembly files in /hwfssz1/jin/20_phyto/27_genomes/01_test
INFO ::: 2022-03-03 15:14:13,607 ::: Found 1 taxa in the DB
INFO ::: 2022-03-03 15:14:13,607 ::: Checking assemblies already processed
INFO ::: 2022-03-03 15:14:13,614 ::: 1 assemblies already processed

INFO ::: 2022-03-03 15:14:13,617 ::: Splitting taxa in groups of singleton, between 2-10 and more than 10 assemblies

INFO ::: 2022-03-03 15:14:13,624 ::: Dereplicating 1 taxa with 2 to 10 assemblies using 5 workers
Traceback (most recent call last):
  File "/hwfssz1/jin/software/miniconda2/envs/derep-genomes/bin/derepG", line 33, in <module>
    sys.exit(load_entry_point('derep-genomes', 'console_scripts', 'derepG')())
  File "/hwfssz1/jin/software/derep-genomes/derep_genomes/__main__.py", line 708, in main
    stats_df = pd.concat([x[3] for x in dfs if not None in dfs])
  File "/hwfssz1/jin/software/miniconda2/envs/derep-genomes/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/hwfssz1/jin/software/miniconda2/envs/derep-genomes/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/hwfssz1/jin/software/miniconda2/envs/derep-genomes/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 374, in __init__
    raise ValueError("All objects passed were None")
ValueError: All objects passed were None

# **packages**
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
arpack                    3.7.0                hdefa2d7_2    conda-forge
boost                     1.70.0           py37h9de70de_1    conda-forge
boost-cpp                 1.70.0               h7b93d67_3    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
capnproto                 0.9.1                h780b84a_1    conda-forge
derep-genomes             0.0.19+0.ge35e89c.dirty           dev_0    <develop>
fastani                   1.32                 he1c1bb9_0    bioconda
glpk                      4.65              h9202a9a_1004    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
igraph                    0.9.2                ha184e22_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
leidenalg                 0.8.4            py37hcd2ae1e_0    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgfortran-ng            11.2.0              h69a702a_12    conda-forge
libgfortran5              11.2.0              h5c6108e_12    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mash                      2.3                  hb340e26_2    bioconda
metis                     5.1.0             h58526e2_1006    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
networkx                  2.6.3                    pypi_0    pypi
numpy                     1.21.5           py37hf2998dd_0    conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
pandas                    1.3.5                    pypi_0    pypi
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
python                    3.7.12          hf930737_100_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-igraph             0.9.1            py37h6c76e3a_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2021.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1                  h46c0cb4_0    conda-forge
scipy                     1.7.3                    pypi_0    pypi
setuptools                60.9.3           py37h89c1867_0    conda-forge
simple-slurm              0.2.2                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.37.0               h9cd32fc_0    conda-forge
suitesparse               5.10.1               h9e50725_1    conda-forge
tbb                       2021.5.0             h4bd325d_0    conda-forge
texttable                 1.6.4              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.50.0                   pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

**Comment by genomewalker** [comment]
Hi @ShangjinTan 

thank you very much. This should be solved in the new version

**Comment by ShangjinTan** [comment]
> Hi @ShangjinTan
> 
> thank you very much. This should be solved in the new version

Yes, it works. Thank you for the quick solution. @genomewalker
